---
apiVersion: v1
kind: Secret
metadata:
  name: user-pass
  annotations:
type: Opaque
stringData:
  key: "AWS"
  secret: ""

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s3artifact
spec:
  type: storage
  params:
    - name: type
      value: s3
    - name: Bucket
      value: s3://pipelinebuilds
    - name: Artifact
      value: release-artifact.tgz
    - name: LocalFile
      value: "remote-file-yay.gz"
  secrets:
    - fieldName: AWS_SECRET_ACCESS_KEY
      secretName: user-pass
      secretKey: secret
    - fieldName: AWS_ACCESS_KEY_ID
      secretName: user-pass
      secretKey: key

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: list-dir
spec:
  steps:
    - name: lsdir
      image: busybox
      command: ['ls', 's3artifact/remote-file-yay.gz']
  inputs:
    resources:
      - name: s3artifact
        type: storage
        targetPath: s3artifact

---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: get-tarball-artifact
spec:
  taskRef:
    name: list-dir
  inputs:
    resources:
    - name: s3artifact
      resourceRef:
        name: s3artifact
