---
apiVersion: v1
kind: Secret
metadata:
  name: user-pass
  annotations:
type: Opaque
stringData:
  key: "YOURKEY"
  secret: "YOURSECRET"

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s3-artifact
spec:
  type: storage
  params:
    - name: type
      value: s3
    - name: bucketname
      value: s3://pipelinebuilds
    - name: artifact
      value: release-artifact.tgz
    - name: location
      value: "remote-file-yay.gz"
    - name: region
      value: us-east-1
  secrets:
    - fieldName: AWS_SECRET_ACCESS_KEY
      secretName: user-pass
      secretKey: secret
    - fieldName: AWS_ACCESS_KEY_ID
      secretName: user-pass
      secretKey: key

---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-tarball
spec:
  steps:
    - name: make-artifact-dir
      image: busybox
      command: ['mkdir', '-p', '/workspace/s3artifacts']
    - name: make-fake-tarball
      image: busybox
      command: ['touch', '/workspace/s3artifacts/empty.gz']  # tests s3 resource
    - name: lsdir
      image: busybox
      command: ['ls']
  outputs:
    resources:
      - name: s3-artifact
        type: storage
        targetPath: /workspace/s3artifacts
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: put-tarball-artifact
spec:
  taskRef:
    name: create-tarball
  outputs:
    resources:
    - name: s3-artifact
      resourceRef:
        name: s3-artifact
